{
	"id": "SUSE-SU-2025:0149-1",
	"modified": "2025-01-16T17:03:39Z",
	"published": "2025-01-16T17:03:39Z",
	"related": [
		"CVE-2024-56374"
	],
	"summary": "Security update for python-Django",
	"details": "This update for python-Django fixes the following issues:\n\n- CVE-2024-56374: Fixed lack of upper bound limit enforcement in strings when performing IPv6 validation that could lead to denial of service (bsc#1235856)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Package Hub 15 SP6",
				"name": "python-Django",
				"purl": "pkg:rpm/suse/python-Django&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Package%20Hub%2015%20SP6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.11-150600.3.15.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-Django": "4.2.11-150600.3.15.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.6",
				"name": "python-Django",
				"purl": "pkg:rpm/opensuse/python-Django&distro=openSUSE%20Leap%2015.6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.11-150600.3.15.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-Django": "4.2.11-150600.3.15.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2025/suse-su-20250149-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1235856"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-56374"
		}
	]
}
