{
	"id": "SUSE-SU-2020:3096-1",
	"modified": "2020-10-29T17:08:08Z",
	"published": "2020-10-29T17:08:08Z",
	"related": [
		"CVE-2019-10906",
		"CVE-2019-8341"
	],
	"summary": "Security update for python-Jinja2",
	"details": "This update for python-Jinja2 fixes the following issues:\n\n- CVE-2019-10906: Fixed a sandbox escape due to information disclosure via str.format (bsc#1132323).\n- CVE-2019-8341: Fixed a command injection in function from_string (bsc#1125815).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Manager Client Tools 12",
				"name": "python-Jinja2",
				"purl": "purl:rpm/suse/python-Jinja2&distro=SUSE%20Manager%20Client%20Tools%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.8-19.20.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-Jinja2": "2.8-19.20.1",
						"python3-Jinja2": "2.8-19.20.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Advanced Systems Management 12",
				"name": "python-Jinja2",
				"purl": "purl:rpm/suse/python-Jinja2&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Advanced%20Systems%20Management%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.8-19.20.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-Jinja2": "2.8-19.20.1",
						"python3-Jinja2": "2.8-19.20.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 12",
				"name": "python-Jinja2",
				"purl": "purl:rpm/suse/python-Jinja2&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.8-19.20.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-Jinja2": "2.8-19.20.1",
						"python3-Jinja2": "2.8-19.20.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20203096-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1125815"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1132323"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-10906"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-8341"
		}
	]
}
