{
	"id": "SUSE-SU-2015:0699-1",
	"modified": "2015-03-12T09:33:36Z",
	"published": "2015-03-12T09:33:36Z",
	"related": [
		"CVE-2014-9130"
	],
	"summary": "Security update for python-PyYAML",
	"details": "\npython-PyYAML was updated to fix one security issue which could have \nallowed an attacker to cause a denial of service by supplying specially \ncrafted strings. (CVE-2014-9130, bsc#921588)\n\nSecurity Issues:\n\n    * CVE-2014-9130\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-9130>\n\n",
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20150699-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/921588"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2014-9130"
		}
	]
}
