{
	"id": "openSUSE-SU-2019:2438-1",
	"modified": "2019-11-05T15:31:23Z",
	"published": "2019-11-05T15:31:23Z",
	"related": [
		"CVE-2019-16056",
		"CVE-2019-16935"
	],
	"summary": "Security update for python3",
	"details": "This update for python3 to 3.6.9 fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-16056: Fixed a parser issue in the email module. (bsc#1149955)\n- CVE-2019-16935: Fixed a reflected XSS in python/Lib/DocXMLRPCServer.py (bsc#1153238).\n\nNon-security issues fixed:\n\n- Fixed regression of OpenSSL 1.1.1b-1 in EVP_PBE_scrypt() with salt=NULL. (bsc#1151490)\n- Improved locale handling by implementing PEP 538.\n\nThis update was imported from the SUSE:SLE-15:Update update project.",
	"affected": [
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.1",
				"name": "python3",
				"purl": "pkg:rpm/opensuse/python3&distro=openSUSE%20Leap%2015.1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.9-lp151.6.4.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.9-lp151.6.4.1",
						"libpython3_6m1_0-32bit": "3.6.9-lp151.6.4.1",
						"python3": "3.6.9-lp151.6.4.1",
						"python3-32bit": "3.6.9-lp151.6.4.1",
						"python3-base": "3.6.9-lp151.6.4.1",
						"python3-base-32bit": "3.6.9-lp151.6.4.1",
						"python3-curses": "3.6.9-lp151.6.4.1",
						"python3-dbm": "3.6.9-lp151.6.4.1",
						"python3-devel": "3.6.9-lp151.6.4.1",
						"python3-idle": "3.6.9-lp151.6.4.1",
						"python3-testsuite": "3.6.9-lp151.6.4.1",
						"python3-tk": "3.6.9-lp151.6.4.1",
						"python3-tools": "3.6.9-lp151.6.4.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.1",
				"name": "python3-base",
				"purl": "pkg:rpm/opensuse/python3-base&distro=openSUSE%20Leap%2015.1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.9-lp151.6.4.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.9-lp151.6.4.1",
						"libpython3_6m1_0-32bit": "3.6.9-lp151.6.4.1",
						"python3": "3.6.9-lp151.6.4.1",
						"python3-32bit": "3.6.9-lp151.6.4.1",
						"python3-base": "3.6.9-lp151.6.4.1",
						"python3-base-32bit": "3.6.9-lp151.6.4.1",
						"python3-curses": "3.6.9-lp151.6.4.1",
						"python3-dbm": "3.6.9-lp151.6.4.1",
						"python3-devel": "3.6.9-lp151.6.4.1",
						"python3-idle": "3.6.9-lp151.6.4.1",
						"python3-testsuite": "3.6.9-lp151.6.4.1",
						"python3-tk": "3.6.9-lp151.6.4.1",
						"python3-tools": "3.6.9-lp151.6.4.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/6PXOI3GEE52ZWA3KKGSYWWLSPBYOIN2G/#6PXOI3GEE52ZWA3KKGSYWWLSPBYOIN2G"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1149121"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1149792"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1149955"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1151490"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1153238"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-16056"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-16935"
		}
	]
}
