{
	"id": "SUSE-SU-2024:1571-1",
	"modified": "2024-05-09T11:18:01Z",
	"published": "2024-05-09T11:18:01Z",
	"related": [
		"CVE-2024-21506"
	],
	"summary": "Security update for python-pymongo",
	"details": "This update for python-pymongo fixes the following issues:\n\n- CVE-2024-21506: Fixed out-of-bounds read in the BSON module (bsc#1222492)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Package Hub 15 SP5",
				"name": "python-pymongo",
				"purl": "pkg:rpm/suse/python-pymongo&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Package%20Hub%2015%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.11.0-150300.3.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python3-pymongo": "3.11.0-150300.3.3.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.5",
				"name": "python-pymongo",
				"purl": "pkg:rpm/opensuse/python-pymongo&distro=openSUSE%20Leap%2015.5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.11.0-150300.3.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python3-pymongo": "3.11.0-150300.3.3.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20241571-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1222492"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-21506"
		}
	]
}
