{
	"id": "SUSE-SU-2024:3297-1",
	"modified": "2024-09-18T10:56:55Z",
	"published": "2024-09-18T10:56:55Z",
	"related": [
		"CVE-2023-29483"
	],
	"summary": "Security update for python-dnspython",
	"details": "This update for python-dnspython fixes the following issue:\n\n- Fix CVE-2023-29483 (bsc#1230353).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 12",
				"name": "python-dnspython",
				"purl": "pkg:rpm/suse/python-dnspython&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.12.0-9.16.2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-dnspython": "1.12.0-9.16.2",
						"python3-dnspython": "1.12.0-9.16.2"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243297-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1230353"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2023-29483"
		}
	]
}
