{
	"id": "openSUSE-SU-2018:0651-1",
	"modified": "2018-03-09T13:07:09Z",
	"published": "2018-03-09T13:07:09Z",
	"related": [
		"CVE-2018-7536",
		"CVE-2018-7537"
	],
	"summary": "Security update for python-Django",
	"details": "This update for python-Django fixes the following issues:\n  Update to 1.11.11\n    * Fixes CVE-2018-7536, CVE-2018-7537\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 12",
				"name": "python-Django",
				"purl": "purl:rpm/suse/python-Django&distro=SUSE%20Package%20Hub%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.11.11-8.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-Django": "1.11.11-8.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2018-7536"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2018-7537"
		}
	]
}
