{
	"id": "openSUSE-SU-2024:0408-1",
	"modified": "2024-12-14T15:01:24Z",
	"published": "2024-12-14T15:01:24Z",
	"related": [
		"CVE-2024-53907"
	],
	"summary": "Security update for python-Django",
	"details": "This update for python-Django fixes the following issues:\n\n- CVE-2024-53907: Fixed potential denial-of-service in django.utils.html.strip_tags() (boo#1234232).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 15 SP5",
				"name": "python-Django",
				"purl": "pkg:rpm/suse/python-Django&distro=SUSE%20Package%20Hub%2015%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.2.28-bp155.7.21.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.5",
				"name": "python-Django",
				"purl": "pkg:rpm/opensuse/python-Django&distro=openSUSE%20Leap%2015.5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.2.28-bp155.7.21.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/VSHKOGLVEWXPEXOIZB4OYAUWF7ICEI4K/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1234232"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-53907"
		}
	]
}
