{
	"id": "openSUSE-SU-2024:14310-1",
	"modified": "2024-09-04T00:00:00Z",
	"published": "2024-09-04T00:00:00Z",
	"related": [
		"CVE-2024-45230",
		"CVE-2024-45231"
	],
	"summary": "python310-Django4-4.2.16-1.1 on GA media",
	"details": "These are all security issues fixed in the python310-Django4-4.2.16-1.1 package on the GA media of openSUSE Tumbleweed.",
	"affected": [
		{
			"package": {
				"ecosystem": "openSUSE:Tumbleweed",
				"name": "python-Django4",
				"purl": "purl:rpm/suse/python-Django4&distro=openSUSE%20Tumbleweed"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.16-1.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python310-Django4": "4.2.16-1.1",
						"python311-Django4": "4.2.16-1.1",
						"python312-Django4": "4.2.16-1.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-45230"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-45231"
		}
	]
}
