{
	"id": "openSUSE-SU-2024:0080-1",
	"modified": "2024-03-11T18:41:01Z",
	"published": "2024-03-11T18:41:01Z",
	"related": [
		"CVE-2024-27351"
	],
	"summary": "Security update for python-Django1",
	"details": "This update for python-Django1 fixes the following issues:\n\n- CVE-2024-27351: Fixed a denial-of-service in regular expression of django.utils.text.Truncator.words() (boo#1220358).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 15 SP5",
				"name": "python-Django1",
				"purl": "purl:rpm/suse/python-Django1&distro=SUSE%20Package%20Hub%2015%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.11.29-bp155.4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python3-Django1": "1.11.29-bp155.4.9.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.5",
				"name": "python-Django1",
				"purl": "purl:rpm/suse/python-Django1&distro=openSUSE%20Leap%2015.5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.11.29-bp155.4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python3-Django1": "1.11.29-bp155.4.9.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/BROIU2USAKIOU6XOT2YPTIGOODLQMAPF/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1220358"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-27351"
		}
	]
}
