{
	"id": "openSUSE-SU-2024:11725-1",
	"modified": "2024-06-15T00:00:00Z",
	"published": "2024-06-15T00:00:00Z",
	"related": [
		"CVE-2021-45115",
		"CVE-2021-45452"
	],
	"summary": "python310-Django-4.0.1-1.1 on GA media",
	"details": "These are all security issues fixed in the python310-Django-4.0.1-1.1 package on the GA media of openSUSE Tumbleweed.",
	"affected": [
		{
			"package": {
				"ecosystem": "openSUSE:Tumbleweed",
				"name": "python-Django",
				"purl": "purl:rpm/suse/python-Django&distro=openSUSE%20Tumbleweed"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.0.1-1.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python310-Django": "4.0.1-1.1",
						"python38-Django": "4.0.1-1.1",
						"python39-Django": "4.0.1-1.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2021-45115"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2021-45452"
		}
	]
}
